<a href="https://colab.research.google.com/github/FranciscoFoz/Projeto_Final_Bootcamp_Data_Science_Alura/blob/main/Notebooks/Projeto_final_Previsao_Admissao_UTI.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# <font color= MediumSpringGreen		size = 6> Bootcamp Data Science Alura - Projeto Final </font>

# <font color= MediumSpringGreen		size = 6>
Previsão da admissão na UTI:
Um modelo de Machine Learning a partir de dados dos pacientes do Hospital Sírio Libanês </font>

Elaborado por [Francisco Foz](https://www.linkedin.com/in/francisco-tadeu-foz/)

Data: 30/01/2022

## <font color= MediumSpringGreen> Introdução

Olá! 

Neste repositório você encontrará o meu projeto final do Bootcamp Data Science 2021-22 da [Alura](https://www.alura.com.br/).

Durante todo o Bootcamp tive a oportunidade de mergulhar no oceano da Ciência de Dados a partir de dados reais da área da saúde em 6 módulos.

___ 

## <font color= MediumSpringGreen> Projeto

### <font color= MediumSpringGreen> Contexto

Devido a pandemia de COVID-19, os hospitais ficaram sobrecarregados faltando recursos de saúde como leitos de UTI, profissionais entre outros. 

Há a necessidade de prever a quantidade necessária de recursos, principalmente de leitos de UTI. 
Para isso foram utilizados dados clínicos individuais de pacientes afim de se estabelecer um modelo e conseguir otimizar a necessidade real da permissão de entrada.

Foram utilizados os dados disponibilizados pelo Hospital Sírio-Libanês no [Kaggle](https://www.kaggle.com/S%C3%ADrio-Libanes/covid19) .

### <font color= MediumSpringGreen> Conjunto de Dados

Ele é formado por dados anônimos do Hospital Sírio-Libanês (São Paulo e Brasília). 

Os dados foram limpos e dimensionados em cada coluna de com o "Min Max Scaler" para ficar entre -1 e 1.

A quantidade de características (colunas) para cada tipo de informação agrupadas são:

*    Informações demográficas do paciente (03)
*    Doenças agrupadas anteriores do paciente (09)
*    Resultados de sangue (36)
*    Sinais vitais (06)

Totalizando 54 características, que ainda se desdobram em sua média, mediana, max, min etc. 

A coluna ICU é o resultado da informação se a pessoa foi ou não para a UTI, a partir da janela "Window" que é a escala de tempo medido de cada linha.

Como abaixo:

Janela:	
* De 0 a 2 horas da admissão
* De 2 a 4 horas da admissão
* De 4 a 6 horas da admissão
* Das 6 às 12 horas da admissão
* Acima de 12 horas da admissão

### <font color= MediumSpringGreen> Desenvolvimento do projeto

Será realizado nas seguintes etapas:

* 1º Notebook: 


* 2º Notebook: 


* 3º Notebook: 



* 4º Notebook:

### <font color= MediumSpringGreen> Bibliotecas utilizadas 



*   Pandas == 1.1.5
*   Numpy == 1.19.5

In [ ]:
import pandas as pd
import numpy as np

## <font color= MediumSpringGreen> Importação de dados

Realizei o download no [Kaggle](https://www.kaggle.com/S%C3%ADrio-Libanes/covid19), do dataset e deixei ele salvo no [repositório](https://github.com/FranciscoFoz/Projeto_Final_Bootcamp_Data_Science_Alura/tree/main/Dados) do meu Github. 

A partir disso, realizei a importação diretamente para o notebook.

In [19]:
dados = pd.read_csv('https://raw.githubusercontent.com/FranciscoFoz/Projeto_Final_Bootcamp_Data_Science_Alura/main/Dados/Kaggle_Sirio_Libanes_ICU_Prediction.csv?token=GHSAT0AAAAAABRAMQJSNGCORBPWJWA4I5L4YPVWM5Q', 
            sep=';')
dados

      PATIENT_VISIT_IDENTIFIER  AGE_ABOVE65  ...    WINDOW  ICU
0                            0            1  ...       0-2    0
1                            0            1  ...       2-4    0
2                            0            1  ...       4-6    0
3                            0            1  ...      6-12    0
4                            0            1  ...  ABOVE_12    1
...                        ...          ...  ...       ...  ...
1920                       384            0  ...       0-2    0
1921                       384            0  ...       2-4    0
1922                       384            0  ...       4-6    0
1923                       384            0  ...      6-12    0
1924                       384            0  ...  ABOVE_12    0

[1925 rows x 231 columns]

## <font color= MediumSpringGreen> 1. Limpeza dos dados

In [20]:
dados.query("WINDOW == '0-2' and ICU == 1")['PATIENT_VISIT_IDENTIFIER'].values

array([  1,  17,  27,  41,  47,  48,  54,  62,  85,  90, 104, 106, 109,
       117, 144, 176, 202, 206, 226, 233, 239, 261, 270, 282, 286, 306,
       315, 329, 359, 362, 366, 379])

In [ ]:
def remover_pacientes_com_primeira_janela_positiva_para_UTI(dados):
  a_remover = dados.query("WINDOW == '0-2' and ICU == 1")['PATIENT_VISIT_IDENTIFIER'].values
  dados_limpos = dados.query("PATIENT_VISIT_IDENTIFIER not in @a_remover")
  return dados_limpos

In [ ]:
dados_sem_pacientes_positivos_na_primeira_janela = remover_pacientes_com_primeira_janela_positiva_para_UTI(dados)

In [ ]:
remover_pacientes_com_primeira_janela_positiva_para_UTI(dados)

      PATIENT_VISIT_IDENTIFIER  AGE_ABOVE65  ...    WINDOW  ICU
0                            0            1  ...       0-2    0
1                            0            1  ...       2-4    0
2                            0            1  ...       4-6    0
3                            0            1  ...      6-12    0
4                            0            1  ...  ABOVE_12    1
...                        ...          ...  ...       ...  ...
1920                       384            0  ...       0-2    0
1921                       384            0  ...       2-4    0
1922                       384            0  ...       4-6    0
1923                       384            0  ...      6-12    0
1924                       384            0  ...  ABOVE_12    0

[1765 rows x 231 columns]

In [ ]:
def prepare_window(rows):
  if(np.any(rows['ICU'])):
    rows.loc[rows['WINDOW']=='0-2','ICU'] = 1
  return rows.loc[rows['WINDOW'] == '0-2']

In [ ]:
dados.groupby('PATIENT_VISIT_IDENTIFIER').apply(prepare_window).head(10)

In [ ]:
dados.head(30)

In [ ]:
def preenche_tabela(dados):
  features_continuas_colunas = dados.iloc[:,13:-2].columns
  features_continuas = dados.groupby('PATIENT_VISIT_IDENTIFIER', as_index=False)[features_continuas_colunas].fillna(method='bfill').fillna(method='ffill')
  features_categoricas = dados.iloc[:,:13]
  saida = dados.iloc[:, -2:]
  dados_finais = pd.concat([features_categoricas,features_continuas,saida],ignore_index=True,axis=1)
  dados_finais.columns = dados.columns
  return dados_finais

In [ ]:
dados_limpos = preenche_tabela(dados)

In [ ]:
dados_limpos = dados_limpos.dropna()

In [ ]:
dados.query('WINDOW == "0-2" and ICU==1')

      PATIENT_VISIT_IDENTIFIER  AGE_ABOVE65  ... WINDOW  ICU
5                            1            1  ...    0-2    1
85                          17            0  ...    0-2    1
135                         27            1  ...    0-2    1
205                         41            1  ...    0-2    1
235                         47            0  ...    0-2    1
240                         48            0  ...    0-2    1
270                         54            1  ...    0-2    1
310                         62            1  ...    0-2    1
425                         85            1  ...    0-2    1
450                         90            0  ...    0-2    1
520                        104            1  ...    0-2    1
530                        106            1  ...    0-2    1
545                        109            0  ...    0-2    1
585                        117            1  ...    0-2    1
720                        144            1  ...    0-2    1
880                        176            1  ...    0-2    1
1010                       202            1  ...    0-2    1
1030                       206            0  ...    0-2    1
1130                       226            1  ...    0-2    1
1165                       233            1  ...    0-2    1
1195                       239            0  ...    0-2    1
1305                       261            0  ...    0-2    1
1350                       270            1  ...    0-2    1
1410                       282            1  ...    0-2    1
1430                       286            0  ...    0-2    1
1530                       306            0  ...    0-2    1
1575                       315            0  ...    0-2    1
1645                       329            1  ...    0-2    1
1795                       359            1  ...    0-2    1
1810                       362            0  ...    0-2    1
1830                       366            0  ...    0-2    1
1895                       379            1  ...    0-2    1

[32 rows x 231 columns]



---



---

In [ ]:
x_columns = dados.describe().columns

dados_limpos = dados.dropna()

In [ ]:
y = dados_limpos['ICU']
x = dados_limpos[x_columns].drop(['ICU','GENDER'],axis=1)

In [ ]:
from sklearn.linear_model import LogisticRegression

modelo = LogisticRegression()
modelo.fit(x,y)

LogisticRegression()

In [ ]:
sum(modelo.predict(x)==y) / len(y) * 100

65.13761467889908

In [ ]:
y.value_counts()

0    281
1    264
Name: ICU, dtype: int64

In [ ]:
from sklearn.dummy import DummyClassifier

modelo = DummyClassifier()
modelo.fit(x,y)
sum(modelo.predict(x)==y) / len(y) * 100

51.559633027522935

In [ ]:
from sklearn.metrics import accuracy_score

accuracy_score(y, modelo.predict(x))

0.5155963302752293



---



---



---

In [ ]:
np.random.seed(3546)

In [ ]:
from sklearn.model_selection import train_test_split

x_train, x_test, y_train, y_test = train_test_split(x, y,stratify=y)

In [ ]:
print(len(x_train),len(y_train))
print(len(x_test),len(y_test))

408 408
137 137

In [ ]:
modelo = LogisticRegression()
modelo.fit(x_train,y_train)
y_prediction = modelo.predict(x_test)
accuracy_score(y_test, y_prediction)

0.6496350364963503

In [ ]:
y_test.value_counts(normalize=True)

0    0.518248
1    0.481752
Name: ICU, dtype: float64



---



---

In [ ]:
dados

      PATIENT_VISIT_IDENTIFIER  AGE_ABOVE65  ...    WINDOW  ICU
0                            0            1  ...       0-2    0
1                            0            1  ...       2-4    0
2                            0            1  ...       4-6    0
3                            0            1  ...      6-12    0
4                            0            1  ...  ABOVE_12    1
...                        ...          ...  ...       ...  ...
1920                       384            0  ...       0-2    0
1921                       384            0  ...       2-4    0
1922                       384            0  ...       4-6    0
1923                       384            0  ...      6-12    0
1924                       384            0  ...  ABOVE_12    0

[1925 rows x 231 columns]